datastax-java-driver {
  basic.request {
    timeout = 30 seconds
    consistency = LOCAL_QUORUM
  }
  advanced.connection {
      max-requests-per-connection = 1024
      max-orphan-requests = 256
      pool {
        local.size = 1
        remote.size = 1
      }
  }
}