quarkus.cassandra.contact-points=localhost:9042,localhost:9043,localhost:9044
quarkus.cassandra.local-datacenter=datacenter1
quarkus.cassandra.keyspace=keyspacedata
quarkus.cassandra.auth.username=cassandra
quarkus.cassandra.auth.password=cassandra

# Configuración de conexión
quarkus.cassandra.connection.init-query-timeout=PT30S


# Puerto de la aplicación
quarkus.http.port=9292
