quarkus.cassandra.contact-points=localhost:9042,localhost:9043,localhost:9044
quarkus.cassandra.local-datacenter=datacenter1
quarkus.cassandra.keyspace=keyspacedata
quarkus.cassandra.auth.username=cassandra
quarkus.cassandra.auth.password=cassandra
quarkus.cassandra.request.consistency=LOCAL_QUORUM

# Configuración de conexión
quarkus.cassandra.connection.init-query-timeout=PT30S
quarkus.cassandra.request.timeout=PT30S
quarkus.cassandra.connection.timeout=PT5S

# Puerto de la aplicación
quarkus.http.port=9292
