
-- 2. INSERT 50 ROW
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (012e3456-e89b-12d3-a456-426614174003, '2024-09', '2024-09-02 09:47:20.058', 'Las Palmas', 'Zaragoza', '2024-11-15', '2024-11-25');
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (012e3456-e89b-12d3-a456-426614174003, '2024-09', '2024-09-04 11:42:27.362', 'Las Palmas', 'Madrid', '2024-12-03', NULL);
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (012e3456-e89b-12d3-a456-426614174003, '2024-09', '2024-09-19 09:39:05.429', 'Zaragoza', 'Alicante', '2024-11-05', NULL);
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (012e3456-e89b-12d3-a456-426614174003, '2024-09', '2024-09-22 18:15:16.405', 'Bilbao', 'Alicante', '2024-11-08', NULL);
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (012e3456-e89b-12d3-a456-426614174003, '2024-10', '2024-10-06 22:24:17.947', 'Alicante', 'Sevilla', '2024-11-23', NULL);
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (012e3456-e89b-12d3-a456-426614174003, '2024-10', '2024-10-25 17:05:54.238', 'Palma de Mallorca', 'Ámsterdam', '2024-12-29', '2025-01-05');
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (012e3456-e89b-12d3-a456-426614174003, '2024-11', '2024-11-08 08:42:12.408', 'Barcelona', 'Málaga', '2024-12-29', '2025-01-06');
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (012e3456-e89b-12d3-a456-426614174003, '2024-11', '2024-11-12 21:04:42.942', 'Málaga', 'Barcelona', '2024-12-27', '2025-01-08');
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (012e3456-e89b-12d3-a456-426614174003, '2024-11', '2024-11-17 23:50:57.982', 'Valencia', 'Milán', '2024-12-04', '2024-12-16');
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (123e4567-e89b-12d3-a456-426614174000, '2024-09', '2024-09-03 15:10:26.497', 'Palma de Mallorca', 'Madrid', '2024-10-01', '2024-10-09');
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (123e4567-e89b-12d3-a456-426614174000, '2024-09', '2024-09-22 17:59:42.106', 'Valencia', 'Ámsterdam', '2024-10-13', NULL);
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (123e4567-e89b-12d3-a456-426614174000, '2024-10', '2024-10-08 09:51:20.410', 'Sevilla', 'Palma de Mallorca', '2024-11-11', '2024-11-19');
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (123e4567-e89b-12d3-a456-426614174000, '2024-10', '2024-10-20 18:31:01.114', 'Bilbao', 'Berlín', '2024-11-03', '2024-11-14');
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (123e4567-e89b-12d3-a456-426614174000, '2024-10', '2024-10-25 13:44:27.348', 'Sevilla', 'Palma de Mallorca', '2024-11-14', '2024-11-17');
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (123e4567-e89b-12d3-a456-426614174000, '2024-11', '2024-11-29 11:49:27.224', 'Alicante', 'Las Palmas', '2024-12-12', '2024-12-15');
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (234e5678-e89b-12d3-a456-426614174007, '2024-10', '2024-10-05 16:08:15.762', 'Bilbao', 'Las Palmas', '2024-12-25', '2024-12-30');
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (234e5678-e89b-12d3-a456-426614174007, '2024-10', '2024-10-07 12:46:59.903', 'Las Palmas', 'Sevilla', '2024-12-13', NULL);
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (234e5678-e89b-12d3-a456-426614174007, '2024-11', '2024-11-05 22:42:33.572', 'Las Palmas', 'Zaragoza', '2025-01-05', NULL);
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (345e6789-e89b-12d3-a456-426614174004, '2024-09', '2024-09-30 22:18:27.713', 'Alicante', 'Milán', '2024-12-08', '2024-12-14');
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (345e6789-e89b-12d3-a456-426614174004, '2024-10', '2024-10-25 18:07:18.445', 'Madrid', 'Málaga', '2025-01-04', '2025-01-14');
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (456e7890-e89b-12d3-a456-426614174001, '2024-09', '2024-09-01 22:39:36.102', 'Sevilla', 'Zaragoza', '2024-10-11', '2024-10-18');
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (456e7890-e89b-12d3-a456-426614174001, '2024-09', '2024-09-02 20:46:21.819', 'Sevilla', 'Berlín', '2024-10-03', '2024-10-07');
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (456e7890-e89b-12d3-a456-426614174001, '2024-09', '2024-09-21 21:53:17.045', 'Valencia', 'Málaga', '2024-10-18', '2024-10-28');
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (456e7890-e89b-12d3-a456-426614174001, '2024-09', '2024-09-28 13:04:38.069', 'Sevilla', 'Las Palmas', '2024-10-20', NULL);
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (456e7890-e89b-12d3-a456-426614174001, '2024-09', '2024-09-29 15:23:18.161', 'Alicante', 'Bilbao', '2024-12-23', NULL);
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (456e7890-e89b-12d3-a456-426614174001, '2024-10', '2024-10-01 16:15:14.142', 'Alicante', 'Londres', '2024-12-22', '2024-12-24');
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (456e7890-e89b-12d3-a456-426614174001, '2024-10', '2024-10-03 23:52:04.778', 'Valencia', 'Sevilla', '2024-12-09', NULL);
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (456e7890-e89b-12d3-a456-426614174001, '2024-10', '2024-10-07 15:32:38.027', 'Alicante', 'Palma de Mallorca', '2024-11-11', '2024-11-17');
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (456e7890-e89b-12d3-a456-426614174001, '2024-10', '2024-10-13 20:38:29.541', 'Alicante', 'Madrid', '2024-11-03', '2024-11-13');
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (456e7890-e89b-12d3-a456-426614174001, '2024-10', '2024-10-23 09:14:04.927', 'Málaga', 'Barcelona', '2025-01-03', '2025-01-15');
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (456e7890-e89b-12d3-a456-426614174001, '2024-10', '2024-10-28 17:53:40.519', 'Valencia', 'Palma de Mallorca', '2024-11-24', '2024-12-08');
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (456e7890-e89b-12d3-a456-426614174001, '2024-11', '2024-11-12 21:39:47.158', 'Sevilla', 'Copenhague', '2024-12-09', NULL);
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (456e7890-e89b-12d3-a456-426614174001, '2024-11', '2024-11-13 09:54:30.227', 'Las Palmas', 'Málaga', '2024-12-29', NULL);
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (456e7890-e89b-12d3-a456-426614174001, '2024-11', '2024-11-15 21:56:40.589', 'Palma de Mallorca', 'Alicante', '2025-01-12', '2025-01-24');
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (678e9012-e89b-12d3-a456-426614174005, '2024-10', '2024-10-15 22:07:15.230', 'Madrid', 'Zaragoza', '2024-11-20', '2024-11-22');
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (678e9012-e89b-12d3-a456-426614174005, '2024-10', '2024-10-28 19:38:16.826', 'Las Palmas', 'Zaragoza', '2024-11-19', NULL);
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (678e9012-e89b-12d3-a456-426614174005, '2024-11', '2024-11-01 11:56:16.182', 'Bilbao', 'Madrid', '2024-11-21', '2024-11-28');
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (678e9012-e89b-12d3-a456-426614174005, '2024-11', '2024-11-03 15:43:19.230', 'Valencia', 'París', '2024-11-15', '2024-11-24');
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (678e9012-e89b-12d3-a456-426614174005, '2024-11', '2024-11-14 11:24:57.590', 'Madrid', 'Las Palmas', '2024-11-21', '2024-12-05');
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (789e0123-e89b-12d3-a456-426614174002, '2024-09', '2024-09-09 17:38:13.734', 'Bilbao', 'Zaragoza', '2024-11-17', '2024-11-19');
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (789e0123-e89b-12d3-a456-426614174002, '2024-10', '2024-10-09 21:13:59.552', 'Sevilla', 'Atenas', '2024-11-24', '2024-12-06');
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (789e0123-e89b-12d3-a456-426614174002, '2024-10', '2024-10-12 19:13:42.273', 'Barcelona', 'Zurich', '2025-01-08', '2025-01-21');
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (789e0123-e89b-12d3-a456-426614174002, '2024-10', '2024-10-17 23:05:48.048', 'Valencia', 'Milán', '2024-11-13', '2024-11-21');
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (789e0123-e89b-12d3-a456-426614174002, '2024-11', '2024-11-14 12:02:19.373', 'Madrid', 'Bruselas', '2025-01-05', '2025-01-10');
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (789e0123-e89b-12d3-a456-426614174002, '2024-11', '2024-11-29 21:01:11.754', 'Palma de Mallorca', 'Estocolmo', '2025-01-06', '2025-01-20');
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (901e2345-e89b-12d3-a456-426614174006, '2024-09', '2024-09-06 16:29:15.895', 'Las Palmas', 'Estocolmo', '2024-11-22', '2024-12-04');
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (901e2345-e89b-12d3-a456-426614174006, '2024-09', '2024-09-18 08:07:04.967', 'Valencia', 'Dublín', '2024-09-29', NULL);
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (901e2345-e89b-12d3-a456-426614174006, '2024-10', '2024-10-03 17:53:40.633', 'Málaga', 'Zurich', '2024-11-03', '2024-11-05');
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (901e2345-e89b-12d3-a456-426614174006, '2024-11', '2024-11-11 20:44:18.567', 'Palma de Mallorca', 'Las Palmas', '2024-12-10', '2024-12-16');
INSERT INTO keyspacedata.search_history (user_id, month_bucket, search_timestamp, origin, destination, departure_date, return_date)
VALUES (901e2345-e89b-12d3-a456-426614174006, '2024-11', '2024-11-18 08:19:18.215', 'Zaragoza', 'Málaga', '2025-01-23', '2025-02-04');
